@startuml
hide circle
hide empty members

class "StanMagazynowy" as StanMagazynowy {
  id_pozycji PK
  nazwa
  ilosc
  prog_alarmowy
}

class "ZapytanieOfertowe" as ZapytanieOfertowe {
  id_zapytania PK
  id_pozycji FK
  status
  data
}

class "Klient" as Klient {
  id_klienta PK
  imie
  nazwisko
  email
  telefon
}

class "Abonament" as Abonament {
  id_abonamentu PK
  id_klienta FK
  okres
  status
  oplata
}

class "Operator" as Operator {
  id_operatora PK
  imie
  nazwisko
  status
}

class "Zlecenie" as Zlecenie {
  id_zlecenia PK
  status
  adres
  kategoria
  typ_powierzchni
  termin
  cena_wstepna
}

class "Platnosc" as Platnosc {
  id_platnosci PK
  id_zlecenia FK
  kwota
  status
  data
}

class "Zdjecie" as Zdjecie {
  id_zdjecia PK
  id_zlecenia FK
  typ
  url_pliku
  data
}

class "Reklamacja" as Reklamacja {
  id_reklamacji PK
  id_zlecenia FK
  opis
  status
  data
}

class "Myjka" as Myjka {
  id_myjki PK
  nr_seryjny
  stan
  ostatni_przeglad
}

class "OdczytIoT" as OdczytIoT {
  id_odczytu PK
  id_myjki FK
  temperatura
  przeplyw
  czas
}

' Relacje bazy danych
StanMagazynowy -right-> ZapytanieOfertowe : "1:N"

Klient -right-> Abonament : "1:N"
Klient --> Zlecenie : "1:N"

Operator -right-> Zlecenie : "1:N"

Myjka --> Zlecenie : "1:N"
Myjka -right-> OdczytIoT : "1:N"

Zlecenie -right-> Platnosc : "1:1..N"
Zlecenie -right-> Zdjecie : "1:N"
Zlecenie -right-> Reklamacja : "1:0..N"

@enduml